### ISSUE TITLE
Just have only one update path

### ISSUE THREAD

**Issue by mehmetoguzderin** [ud-turkic/udtw23#10]
Right now, README advises authors to either PR to main or push commits to dev directly. This approach means someone should rebase dev with main and vice versa every now and then, with further risks to potential problems in Git history.

Recently, GitHub made it easier for people to sync their forks only through Web UI and create commits even when they are organization members of the subject repository.

Suggestion:
* Make "main" a [protected branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) so that only PRs can write to it.
* Delete "dev" and any suggestions to maintain a dev in the ud-turkic/udtw23 itself.
* Add a small guide to syncing forks.

These measures effectively:
* Removes confusion about following one way or another,
* Eliminate potential of total corruption suddenly because of any Git nuance during merges,
* Circulates more copies of this repository by people who would like to contribute.

We should be able to do technical guidance and tutorials if people feel uncomfortable with GitHub UI.

**Comment by furkanakkurt1335** [comment]
I've just protected the `main` branch.

What do you mean by "one update path"?

Can you prepare a small document for people as to how to go about this?

**Comment by mehmetoguzderin** [comment]
@furkanakkurt1335 thanks for adding protection to the main and changing the README. I think latest commit https://github.com/ud-turkic/udtw23/commit/be12625d402d18a5fc9642d8125b82e57ed4cf7b to README.md does interpret my intention about "one update path" correctly since it removes the clause about dev branch: PR is the way to go to main.

I do intend to create a step-by-step guide about this. I'll PR once ready (most likely not within next 2 weeks).

**Comment by furkanakkurt1335** [comment]
Great! We can close this issue after the eventual PR for documenting the technicalities regarding this gets accepted.

**Comment by furkanakkurt1335** [comment]
Is there any progress on this, @mehmetoguzderin ? We can close the issue still, I'm not aware of any problems encountered yet.

**Comment by mehmetoguzderin** [comment]
Last status was not so much about an issue but about documenting the flow. Closing
