### ISSUE TITLE
write / finish abstract for UniDive 2nd general meeting

### ISSUE THREAD

**Issue by furkanakkurt1335** [ud-turkic/udtw23#22]
We talked in the meeting to write an abstract to [UniDive 2nd general meeting](https://unidive.lisn.upsaclay.fr/doku.php?id=meetings:general_meetings:2nd_unidive_general_meeting_call_for_abstracts). Everyone can contribute. It will be about 2 pages.

Overleaf edit access link: [here](https://www.overleaf.com/5335652146drnffzjczbcd#25663e).
Overleaf project link: [here](https://www.overleaf.com/project/64f856dea3ac76360acd8ed7).

**Comment by furkanakkurt1335** [comment]
We will include each person willing to be included in the submission as an author.

**Comment by mehmetoguzderin** [comment]
I'd like to edit to include two simple example phrases (unlikely to bloat the paper, just inline phrases not even sentence nor diagram) to exemplify a historical Turkic language through Old Turkish with Old Turkic script once the abstract had its first pass for skeleton etc., and willing to be included as author

**Comment by furkanakkurt1335** [comment]
The abstract was accepted. Now, we will work on finishing it for the final submission, due Jan 12.

**Comment by furkanakkurt1335** [comment]
I've asked for the abstract page-limit, waiting for a response; specifically, whether the appendix is included in the limit.

**Comment by furkanakkurt1335** [comment]
I didn't get any response for the previous comment. The final abstract has been submitted. 

It seems the deadline was extended. If I get a response that would invalidate our latest submission, we can reopen this issue.
